spring:
  #静态资源处理
  web:
    resources:
      #启用静态资源处理器，默认开启
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间（秒）
          max-age: 3600
      chain:
        #资源链
        cache: true
        #启用资源链 默认禁用
        enabled: true
        #启用压缩资源，默认禁用
        compressed: true
      static-locations: classpath:/static/
  #  thymeleaf配置
  thymeleaf:
    #  关闭thymeleaf缓存
    cache: false
  #    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skill?useUnicode=true&&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: swd19980726
    hikari:
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认是10分钟（600000）
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，默认是30分钟（1800000）
      max-lifetime: 1800000
      # 连接超时时间，默认是30秒
      connection-timeout: 30000
      # 测试连接是否可用（心跳日记）
      connection-test-query: SELECT 1
  redis:
    #主机位置
    host: 192.168.117.130
    #端口配置
    port: 6379
    #默认操作数据库
    database: 0
    #连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #z最大空闲连接数
        max-idle: 200
        #最大连接阻塞等待时间
        #最大连接数
        max-active: 8
        #最小空闲连接数
        min-idle: 5
        max-wait: 10000ms
    password: swd19980726
  #rabbitmq相关配置
  rabbitmq:
    #服务器位置
    host: 192.168.117.129
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口号
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者，每次只处理一条消息，处理完成后再继续下一条消息
        prefetch: 1
        #启动的时候，是否默认启动容器，默认为true
        auto-startup: true
        #当消息被拒绝时，是否重新进入队列，
        default-requeue-rejected: true
    template:
      retry:
        #是否开启重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #默认重试次数，默认是3
        max-attempts: 3
        #最大间隔重试时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数，默认1
        multiplier: 1






# mybatis-plus配置
mybatis-plus:
  # 配置mapper.xml存放的位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名是类目 ）
  type-aliases-package: com.sjtu.seckill.pojo

# Mybatis SQL打印（方法接口所在的包，不是mapper.xml所在的包）
logging:
  level:
    com.sjtu.seckill.mapper: debug
